GET http://localhost:1337/cards

###
GET http://localhost:1337/cards/34541863
###
GET http://localhost:1337/updateCards
###
GET http://localhost:1337/forceUpdate
###

GET http://localhost:1337/collection

###

GET http://localhost:1337/collection?page=1&limit=7

###

GET http://localhost:1337/decks

###
POST http://localhost:1337/collection
Content-Type: application/json

{
    "name": "Fluffal Bear",
    "id": "03841833",
    "amount": 2
}
###
PATCH http://localhost:1337/collection/03841833
Content-Type: application/json

{
    "id": "03841833",
    "amount": 1
}
###
POST http://localhost:1337/collection
Content-Type: application/json

{
    "id": "03841833",
    "amount": 3
}
###
POST http://localhost:1337/decks
Content-Type: application/json

{
    "name": "Crusadia",
    "description": "Crusadia Deck",
    "thumbnail": "https://storage.googleapis.com/ygoprodeck.com/pics/45002991.jpg",
    "cards": [
        {"name": "Crusadia Equimax", "id": "45002991", "deckType": "1", "amount": 3}
    ]
}